### ISSUE TITLE
How can I delete a shader?

### ISSUE THREAD

**Issue by DanyMotilla** [ShaderFrog/editor#3]
I cant find the button to delete a shader project.

**Comment by AndrewRayCode** [comment]
I will add this feature for users - currently it's an admin only feature

**Comment by AndrewRayCode** [comment]
You can now delete shaders from your account profile page https://shaderfrog.com/2/members/account

<img width="862" alt="delete" src="https://github.com/ShaderFrog/editor/assets/79215/a99906ec-ba72-4670-853d-8a22c49eb723">

And in the editor itself under the Shader > Metadata tab

<img width="898" alt="Screen Shot 2024-03-26 at 7 55 29 PM" src="https://github.com/ShaderFrog/editor/assets/79215/6ed51b7d-c213-48a0-8a90-e70966680c8d">
