### ISSUE TITLE
Literal values available to multiple inputs

### ISSUE THREAD

**Issue by yoiang** [ShaderFrog/editor#7]
Hello! Thanks so much for making ShaderFrog, I'm learning version 2 right now and it's so much fun.

One thing I think would help myself and maybe others work more modularly is the ability to have nodes' outputs flow into multiple other nodes' inputs, rather than it being only 1:1 as it appears to be now. Granted this might be really complex for functional nodes I was thinking a first step that would save a lot of duplication and potentially be more simple to build would be sharing literal values. Currently keeping two literal values in sync between fragment and vertex nodes can be a little bit of a pain and feels not as intuitive with flow based visual programming expectations.

Thanks so much for your time!

**Comment by AndrewRayCode** [comment]
Thank you very much for taking the time to dive into the UI and file these bugs. I featured your shader on the homepage! You are the first user to really dig into the 2.0 UI so I really appreciate you filing issues with your exploration. I also want to be up front that lots of the UI is clunky, or non-obvious, and there are lots of concepts like “strategies”/“backfilling” that have zero documentation and aren’t obvious how to use in the UI now.

I think this specific request isn’t too much of a lift. I intentionally prevent duplicate outputs in the graph config (the graph uses [xyflow](https://www.xyflow.com)). In the end those inputs essentially [just update the material’s uniforms by node name](https://github.com/ShaderFrog/editor/blob/d633c1dedb4e5983dcc5673f972bac7a009b0753/src/editor-engine-plugins/three/ThreeComponent.tsx#L480) so this may just work with a config change. 

Duplicating functional node outputs *might* just work - it will duplicate the function call to the other shader for now, but I’m not focused on efficiency yet. I did try recently try to automatically assign the inlined other shader function call to a variable rather, and inject that variable where the other shader is plugged, but I haven’t completed that refactor yet.

The real potential issue is that when nodes are composed, there is a lot of mutation of the node data. If a node’s output is duplicated, its AST will likely get manipulated twice. But I will test it.

**Comment by AndrewRayCode** [comment]
Done. Outputs can now have multiple edges. Inputs can only have one edge flowing to them.

<img width="1244" alt="image" src="https://github.com/user-attachments/assets/f5189705-1a35-4b0c-a0da-8f5676c05cb3">

This also applies to code nodes, although a code node injected into another node twice causes an error, because it duplicates the function definitions of the code node.
