### ISSUE TITLE
Removing old inputs

### ISSUE THREAD

**Issue by yoiang** [ShaderFrog/editor#8]
Hello! I was wondering, is there a way of updating a fragment node whose input has been rename or removed in code so that the graph view editor doesn't keep these old inputs around?

Thanks again!

**Comment by AndrewRayCode** [comment]
This is an internal TODO I have to complete, there is not currently a way to remove stale inputs. My horrible hack workaround right now is to fully recreate the node.

**Comment by AndrewRayCode** [comment]
![delete-inputs](https://github.com/user-attachments/assets/e16336da-baa9-4119-bf96-d1a49fdb19ce)

You can now delete inputs under the config section of each node.

Note that if you delete an input found by a strategy, if the strategy finds that same input again, it will come back instantly after you delete it

**Comment by yoiang** [comment]
Wonderful, thank you for this 💫
